/**
 * Master registry of all CalcUnit calculators.
 * Each entry is the source of truth for routing, SEO, and schema lookup.
 * "hasSchema: true" means a full interactive JSON schema exists in /lib/schemas/.
 */

export interface RegistryEntry {
  slug: string;
  name: string;
  category: string;
  subcategory?: string;
  icon: string;
  shortDesc: string;
  formula?: string;
  tags: string[];
  hasSchema?: boolean;
  related?: string[];
}

export const ALL_CALCULATORS: RegistryEntry[] = [
  // ─── MATH ────────────────────────────────────────────────────────────────────
  { slug: "square-root-calculator",      name: "Square Root Calculator",       category: "math", icon: "√",  shortDesc: "Find the square root of any number instantly.",                 formula: "√x",                    tags: ["square root", "radical", "math"], hasSchema: true  },
  { slug: "quadratic-formula-calculator",name: "Quadratic Formula Calculator", category: "math", icon: "📐", shortDesc: "Solve any quadratic equation ax² + bx + c = 0.",               formula: "x = (-b ± √(b²-4ac)) / 2a", tags: ["quadratic", "algebra", "equation"], hasSchema: true },
  { slug: "percentage-calculator",       name: "Percentage Calculator",        category: "math", icon: "%",  shortDesc: "Calculate percentages, percentage of, and percent change.",     formula: "P% of X = (P/100) × X", tags: ["percent", "percentage", "math"], hasSchema: true  },
  { slug: "percentage-change-calculator",name: "Percentage Change Calculator", category: "math", icon: "📈", shortDesc: "Find the percentage increase or decrease between two values.",   formula: "((New-Old)/Old) × 100", tags: ["percentage change", "percent increase"], hasSchema: true },
  { slug: "area-of-circle-calculator",  name: "Area of Circle Calculator",    category: "math", icon: "⭕", shortDesc: "Calculate the area of a circle using radius or diameter.",       formula: "A = πr²",               tags: ["circle", "area", "geometry"], hasSchema: true },
  { slug: "slope-calculator",           name: "Slope Calculator",             category: "math", icon: "📉", shortDesc: "Find the slope of a line between two points.",                  formula: "m = (y₂-y₁)/(x₂-x₁)",  tags: ["slope", "gradient", "line", "algebra"], hasSchema: true },
  { slug: "mean-calculator",            name: "Mean Calculator",              category: "math", icon: "∑",  shortDesc: "Calculate the arithmetic mean (average) of a set of numbers.",  formula: "Mean = Σx / n",         tags: ["mean", "average", "statistics"], hasSchema: true },
  { slug: "percent-error-calculator",   name: "Percent Error Calculator",     category: "math", icon: "⚠️", shortDesc: "Calculate the percentage error between observed and actual.",   formula: "|Observed-Actual|/Actual × 100", tags: ["percent error", "error", "accuracy"], hasSchema: true },
  { slug: "area-of-rectangle-calculator",name:"Area of Rectangle Calculator", category: "math", icon: "▭",  shortDesc: "Find the area of a rectangle from length and width.",           formula: "A = l × w",             tags: ["rectangle", "area", "geometry"], hasSchema: true },
  { slug: "volume-of-sphere-calculator",name: "Volume of Sphere Calculator",  category: "math", icon: "🌐", shortDesc: "Calculate the volume of a sphere from its radius.",             formula: "V = (4/3)πr³",          tags: ["sphere", "volume", "geometry"], hasSchema: true },
  { slug: "volume-of-cylinder-calculator",name:"Volume of Cylinder Calculator",category:"math", icon: "🥫", shortDesc: "Calculate the volume of a cylinder from radius and height.",    formula: "V = πr²h",              tags: ["cylinder", "volume", "geometry"], hasSchema: true },
  { slug: "triangle-area-calculator",   name: "Triangle Area Calculator",     category: "math", icon: "△",  shortDesc: "Find the area of any triangle using base, height, or sides.",  formula: "A = ½ × b × h",         tags: ["triangle", "area", "geometry"], hasSchema: true },
  { slug: "pythagorean-theorem",        name: "Pythagorean Theorem Calculator",category:"math", icon: "📐", shortDesc: "Find the missing side of a right triangle using a² + b² = c².", formula: "a² + b² = c²",          tags: ["pythagorean", "right triangle", "hypotenuse", "geometry"], hasSchema: true },
  { slug: "lcm-calculator",             name: "LCM Calculator",               category: "math", icon: "🔢", shortDesc: "Find the Least Common Multiple of two or more numbers.",       formula: "LCM(a,b) = |a×b| / GCD(a,b)", tags: ["lcm", "least common multiple"], hasSchema: true },
  { slug: "gcf-calculator",             name: "GCF Calculator",               category: "math", icon: "🔢", shortDesc: "Find the Greatest Common Factor (GCD) of numbers.",            formula: "Euclidean Algorithm",   tags: ["gcf", "gcd", "greatest common divisor"], hasSchema: true },
  { slug: "factorial-calculator",       name: "Factorial Calculator",         category: "math", icon: "!",  shortDesc: "Calculate n! for any non-negative integer.",                   formula: "n! = n × (n-1) × ... × 1", tags: ["factorial", "combinatorics"], hasSchema: true },
  { slug: "fraction-to-decimal",        name: "Fraction to Decimal",          category: "math", icon: "½",  shortDesc: "Convert any fraction to a decimal number.",                    formula: "Decimal = Numerator ÷ Denominator", tags: ["fraction", "decimal", "convert"], hasSchema: true },
  { slug: "perimeter-calculator",       name: "Perimeter Calculator",         category: "math", icon: "📏", shortDesc: "Calculate the perimeter of rectangles, squares, and triangles.",formula: "P = 2(l+w)",            tags: ["perimeter", "geometry"], hasSchema: true },
  { slug: "adding-fractions-calculator",name: "Adding Fractions Calculator",  category: "math", icon: "½",  shortDesc: "Add two or more fractions and get the simplified result.",      formula: "a/b + c/d = (ad+bc)/bd", tags: ["fractions", "add", "simplify"], hasSchema: true },
  { slug: "absolute-value-calculator",  name: "Absolute Value Calculator",    category: "math", icon: "|x|",shortDesc: "Find the absolute value of any number.",                       formula: "|x| = x if x≥0, -x if x<0", tags: ["absolute value", "modulus"], hasSchema: true },
  { slug: "rounding-calculator",        name: "Rounding Calculator",          category: "math", icon: "≈",  shortDesc: "Round numbers to any decimal place or significant figure.",    formula: "Standard rounding rules", tags: ["round", "decimal", "significant figures"], hasSchema: true },
  { slug: "scientific-notation-calculator",name:"Scientific Notation Calculator",category:"math",icon:"🔬",shortDesc:"Convert numbers to and from scientific notation.",              formula: "a × 10^n",              tags: ["scientific notation", "exponent"], hasSchema: true },
  { slug: "exponents-calculator",       name: "Exponents Calculator",         category: "math", icon: "xⁿ", shortDesc: "Calculate the result of a base raised to any power.",          formula: "aⁿ = a × a × ... × a", tags: ["exponent", "power", "algebra"], hasSchema: true },
  { slug: "modulo-calculator",          name: "Modulo Calculator",            category: "math", icon: "%",  shortDesc: "Find the remainder when dividing two integers.",                formula: "a mod b = r",           tags: ["modulo", "remainder", "division"], hasSchema: true },
  { slug: "prime-number-calculator",    name: "Prime Number Calculator",      category: "math", icon: "🔢", shortDesc: "Check if a number is prime and find prime factors.",            formula: "Sieve of Eratosthenes", tags: ["prime", "number theory"], hasSchema: true },
  { slug: "long-division",             name: "Long Division Calculator",      category: "math", icon: "÷",  shortDesc: "Solve long division step by step with remainder.",              formula: "Dividend ÷ Divisor = Quotient R Remainder", tags: ["division", "long division"], hasSchema: true },
  { slug: "long-multiplication",       name: "Long Multiplication Calculator",category: "math", icon: "×",  shortDesc: "Multiply large numbers with step-by-step working.",             formula: "Column multiplication", tags: ["multiplication", "long multiplication"], hasSchema: true },
  { slug: "long-addition",             name: "Long Addition Calculator",      category: "math", icon: "+",  shortDesc: "Add large numbers with column addition shown step by step.",   formula: "Column addition",       tags: ["addition", "long addition"], hasSchema: true },
  { slug: "long-subtraction",          name: "Long Subtraction Calculator",   category: "math", icon: "−",  shortDesc: "Subtract large numbers with borrowing shown step by step.",    formula: "Column subtraction",    tags: ["subtraction", "long subtraction"], hasSchema: true },
  { slug: "cube-root-calculator",      name: "Cube Root Calculator",          category: "math", icon: "∛",  shortDesc: "Calculate the cube root of any number.",                       formula: "∛x = x^(1/3)",         tags: ["cube root", "radical"], hasSchema: true },
  { slug: "square-calculator",         name: "Square Calculator",             category: "math", icon: "x²", shortDesc: "Square any number — compute x².",                             formula: "x² = x × x",           tags: ["square", "power", "algebra"], hasSchema: true },
  { slug: "completing-square-calculator",name:"Completing the Square",        category: "math", icon: "📐", shortDesc: "Convert a quadratic to vertex form by completing the square.",  formula: "ax² + bx + c → a(x+h)² + k", tags: ["completing square", "quadratic", "algebra"], hasSchema: true },
  { slug: "expanded-form",             name: "Expanded Form Calculator",      category: "math", icon: "🔢", shortDesc: "Write any number in expanded form.",                           formula: "1234 = 1000+200+30+4", tags: ["expanded form", "place value"], hasSchema: true },
  { slug: "place-value",               name: "Place Value Calculator",        category: "math", icon: "🔢", shortDesc: "Find the place value of each digit in a number.",              formula: "Ones, Tens, Hundreds...", tags: ["place value", "digits"], hasSchema: true },
  { slug: "ratio-calculator",          name: "Ratio Calculator",              category: "math", icon: ":",  shortDesc: "Simplify ratios and solve ratio problems.",                     formula: "a:b = ka:kb",           tags: ["ratio", "proportion", "simplify"], hasSchema: true },
  { slug: "proportion-calculator",     name: "Proportion Calculator",         category: "math", icon: "⚖️", shortDesc: "Solve for the unknown in a proportion equation.",               formula: "a/b = c/d → d = bc/a", tags: ["proportion", "ratio", "solve"], hasSchema: true },
  { slug: "common-factors",            name: "Common Factors Calculator",     category: "math", icon: "🔢", shortDesc: "List all common factors of two or more numbers.",               formula: "List factors of each, find shared", tags: ["common factors", "divisors"], hasSchema: true },
  { slug: "equivalent-fractions",      name: "Equivalent Fractions",         category: "math", icon: "=",  shortDesc: "Find equivalent fractions for any given fraction.",             formula: "a/b = (a×k)/(b×k)",    tags: ["equivalent fractions", "fractions"], hasSchema: true },
  { slug: "fraction-to-percent",       name: "Fraction to Percent",          category: "math", icon: "%",  shortDesc: "Convert fractions to percentages quickly.",                    formula: "(a/b) × 100 = %",       tags: ["fraction", "percent", "convert"], hasSchema: true },
  { slug: "percent-to-decimal",        name: "Percent to Decimal",           category: "math", icon: "→",  shortDesc: "Convert percentages to decimal form.",                         formula: "% ÷ 100 = Decimal",    tags: ["percent", "decimal", "convert"], hasSchema: true },
  { slug: "decimal-to-fraction",       name: "Decimal to Fraction",          category: "math", icon: "½",  shortDesc: "Convert any decimal number to a fraction in simplest form.",   formula: "0.75 = 75/100 = 3/4", tags: ["decimal", "fraction", "convert"], hasSchema: true },
  { slug: "decimal-to-percent",        name: "Decimal to Percent",           category: "math", icon: "%",  shortDesc: "Convert decimal numbers to percentages.",                       formula: "Decimal × 100 = %",    tags: ["decimal", "percent", "convert"], hasSchema: true },
  { slug: "mixed-numbers",             name: "Mixed Numbers Calculator",      category: "math", icon: "½",  shortDesc: "Add, subtract, multiply, and divide mixed numbers.",           formula: "Convert to improper then operate", tags: ["mixed numbers", "fractions"], hasSchema: true },
  { slug: "complex-fractions",         name: "Complex Fractions Calculator",  category: "math", icon: "½",  shortDesc: "Simplify complex fractions with fractions in numerator or denominator.", formula: "(a/b)/(c/d) = ad/bc", tags: ["complex fractions", "fractions"], hasSchema: true },
  { slug: "significant-figures",       name: "Significant Figures Calculator",category:"math",  icon: "0",  shortDesc: "Round numbers to a specified number of significant figures.",   formula: "Sig fig rules",        tags: ["significant figures", "precision"], hasSchema: true },
  { slug: "exponential-notation",      name: "Exponential Notation Calculator",category:"math", icon: "10^", shortDesc: "Convert numbers to and from exponential notation.",            formula: "N = a × bᶜ",           tags: ["exponential notation", "scientific notation"], hasSchema: true },
  { slug: "adding-machine-calculator", name: "Adding Machine Calculator",     category: "math", icon: "🧮", shortDesc: "Add up a list of numbers like a traditional adding machine.",   formula: "Running total",        tags: ["adding machine", "sum", "total"], hasSchema: true },
  { slug: "unit-rate",                 name: "Unit Rate Calculator",          category: "math", icon: "÷",  shortDesc: "Calculate the unit rate for any ratio.",                       formula: "Unit Rate = Quantity / Units", tags: ["unit rate", "ratio", "rate"], hasSchema: true },
  { slug: "diamond-problem-solver",    name: "Diamond Problem Solver",        category: "math", icon: "◆",  shortDesc: "Solve diamond problems: find two numbers given their sum and product.", formula: "product & sum → factors", tags: ["diamond problem", "factoring", "algebra"], hasSchema: true },
  { slug: "roman-numeral",             name: "Roman Numeral Converter",       category: "math", icon: "Ⅻ", shortDesc: "Convert numbers to Roman numerals and back.",                  formula: "I=1, V=5, X=10, L=50...", tags: ["roman numeral", "convert"], hasSchema: true },
  { slug: "multiples-calculator",      name: "Multiples Calculator",          category: "math", icon: "×",  shortDesc: "List the first N multiples of any number.",                    formula: "Multiples of n: n, 2n, 3n...", tags: ["multiples", "times table"], hasSchema: true },
  { slug: "surface-area-sphere",       name: "Surface Area of Sphere",        category: "math", icon: "🌐", shortDesc: "Calculate the surface area of a sphere from its radius.",           formula: "SA = 4πr²",              tags: ["surface area", "sphere", "geometry"], hasSchema: true },
  { slug: "surface-area-cylinder",     name: "Surface Area of Cylinder",      category: "math", icon: "🥫", shortDesc: "Calculate the total surface area of a cylinder.",                  formula: "SA = 2πr(r+h)",          tags: ["surface area", "cylinder", "geometry"], hasSchema: true },
  { slug: "volume-cone",               name: "Volume of Cone Calculator",     category: "math", icon: "🍦", shortDesc: "Calculate the volume of a cone from radius and height.",            formula: "V = ⅓πr²h",             tags: ["volume", "cone", "geometry"], hasSchema: true },
  { slug: "trapezoid-area",            name: "Trapezoid Area Calculator",     category: "math", icon: "⏢", shortDesc: "Find the area of a trapezoid from parallel sides and height.",      formula: "A = ½(a+b)×h",          tags: ["trapezoid", "area", "geometry"], hasSchema: true },
  { slug: "ellipse-area",              name: "Ellipse Area Calculator",       category: "math", icon: "⭕", shortDesc: "Calculate the area and perimeter of an ellipse.",                  formula: "A = πab",                tags: ["ellipse", "area", "geometry"], hasSchema: true },
  { slug: "combinations-calculator",   name: "Combinations Calculator",      category: "math", icon: "🔀", shortDesc: "Calculate the number of ways to choose r items from n items.",    formula: "C(n,r) = n! / r!(n-r)!", tags: ["combinations", "choose", "combinatorics"], hasSchema: true },
  { slug: "permutations-calculator",   name: "Permutations Calculator",      category: "math", icon: "🔢", shortDesc: "Calculate ordered arrangements of r items from n items.",          formula: "P(n,r) = n! / (n-r)!",  tags: ["permutations", "arrangements", "combinatorics"], hasSchema: true },
  { slug: "arithmetic-sequence",       name: "Arithmetic Sequence Calculator",category:"math",  icon: "➕", shortDesc: "Find any term and sum of an arithmetic sequence.",                formula: "aₙ = a₁ + (n-1)d",      tags: ["arithmetic sequence", "series", "math"], hasSchema: true },
  { slug: "geometric-sequence",        name: "Geometric Sequence Calculator", category: "math", icon: "✖️", shortDesc: "Find any term and sum of a geometric sequence.",                 formula: "aₙ = a₁ × rⁿ⁻¹",       tags: ["geometric sequence", "series", "math"], hasSchema: true },
  { slug: "fibonacci-calculator",      name: "Fibonacci Calculator",          category: "math", icon: "🌀", shortDesc: "Calculate Fibonacci numbers and the golden ratio approximation.",  formula: "F(n) = F(n-1) + F(n-2)", tags: ["fibonacci", "sequence", "golden ratio", "math"], hasSchema: true },
  { slug: "cross-product-calculator",  name: "Cross Product Calculator",      category: "math", icon: "✕",  shortDesc: "Calculate the cross product of two 3D vectors.",                  formula: "A×B = (a₂b₃-a₃b₂, ...)", tags: ["cross product", "vector", "3d", "math"], hasSchema: true },
  { slug: "surface-area-cube",         name: "Surface Area of Cube",          category: "math", icon: "📦", shortDesc: "Calculate surface area and volume of a cube from edge length.",    formula: "SA = 6a²",               tags: ["cube", "surface area", "geometry"], hasSchema: true },
  { slug: "volume-pyramid",            name: "Volume of Pyramid Calculator",  category: "math", icon: "🔺", shortDesc: "Calculate the volume of a rectangular pyramid.",                   formula: "V = ⅓×l×w×h",           tags: ["pyramid", "volume", "geometry"], hasSchema: true },
  { slug: "regular-polygon-area",      name: "Regular Polygon Area",          category: "math", icon: "⬡",  shortDesc: "Calculate the area of any regular polygon by sides and length.",  formula: "A = ns²/(4·tan(π/n))",   tags: ["polygon", "area", "geometry", "hexagon"], hasSchema: true },

  // ─── ALGEBRA ─────────────────────────────────────────────────────────────────
  { slug: "linear-equation-solver",     name: "Linear Equation Solver",       category: "algebra", icon: "=",  shortDesc: "Solve linear equations with one or two variables.",          formula: "ax + b = c → x = (c-b)/a", tags: ["linear equation", "algebra", "solve"], hasSchema: true },
  { slug: "cubic-equation-calculator",  name: "Cubic Equation Calculator",    category: "algebra", icon: "x³", shortDesc: "Find all roots of a cubic equation ax³ + bx² + cx + d = 0.", formula: "Cardano's formula",     tags: ["cubic equation", "roots", "algebra"], hasSchema: true },
  { slug: "system-of-equations",        name: "System of Equations Calculator",category:"algebra", icon: "⟨⟩", shortDesc: "Solve 2×2 systems of equations by substitution or elimination.", formula: "Gaussian elimination", tags: ["system of equations", "algebra", "solve"], hasSchema: true },
  { slug: "polynomial-calculator",      name: "Polynomial Calculator",        category: "algebra", icon: "p(x)",shortDesc: "Add, subtract, multiply, and factor polynomials.",             formula: "Standard polynomial ops", tags: ["polynomial", "algebra"], hasSchema: true },
  { slug: "factoring-calculator",       name: "Factoring Calculator",         category: "algebra", icon: "✕",  shortDesc: "Factor any polynomial expression completely.",                formula: "GCF, trinomial, difference of squares", tags: ["factoring", "polynomial", "algebra"], hasSchema: true },
  { slug: "foil-method-calculator",     name: "FOIL Method Calculator",       category: "algebra", icon: "(a)(b)", shortDesc: "Multiply two binomials using the FOIL method.",           formula: "(a+b)(c+d) = ac+ad+bc+bd", tags: ["foil", "binomial", "algebra"], hasSchema: true },
  { slug: "difference-of-two-squares",  name: "Difference of Two Squares",    category: "algebra", icon: "²",  shortDesc: "Factor expressions in the form a² - b².",                   formula: "a² - b² = (a+b)(a-b)",  tags: ["difference of squares", "factoring"], hasSchema: true },
  { slug: "dot-product-calculator",     name: "Dot Product Calculator",       category: "algebra", icon: "·",  shortDesc: "Calculate the dot product of two vectors.",                  formula: "A·B = Σ(aᵢ × bᵢ)",    tags: ["dot product", "vector", "algebra"], hasSchema: true },
  { slug: "logarithm-equation-calculator",name:"Logarithm Equation Calculator",category:"algebra",icon:"log",  shortDesc: "Solve logarithmic equations and evaluate log expressions.",  formula: "logₐ(b) = ln(b)/ln(a)", tags: ["logarithm", "log", "algebra"], hasSchema: true },
  { slug: "fractional-exponents",       name: "Fractional Exponents Calculator",category:"algebra",icon:"xⁿ", shortDesc: "Calculate values with fractional and negative exponents.",    formula: "x^(m/n) = ⁿ√(xᵐ)",    tags: ["fractional exponents", "radicals"], hasSchema: true },
  { slug: "radicals-root-calculator",   name: "Radicals & Roots Calculator",  category: "algebra", icon: "√",  shortDesc: "Simplify radicals and compute nth roots.",                   formula: "ⁿ√x = x^(1/n)",        tags: ["radical", "root", "simplify"], hasSchema: true },
  { slug: "fifth-root-calculator",      name: "Fifth Root Calculator",        category: "algebra", icon: "⁵√", shortDesc: "Find the fifth root of any number.",                         formula: "⁵√x = x^(1/5)",        tags: ["fifth root", "radical"], hasSchema: true },
  { slug: "fourth-root-calculator",     name: "Fourth Root Calculator",       category: "algebra", icon: "⁴√", shortDesc: "Find the fourth root of any number.",                        formula: "⁴√x = x^(1/4)",        tags: ["fourth root", "radical"], hasSchema: true },
  { slug: "large-exponents-calculator", name: "Large Exponents Calculator",   category: "algebra", icon: "ⁿ",  shortDesc: "Compute very large exponent values accurately.",             formula: "Modular exponentiation", tags: ["large exponents", "power"], hasSchema: true },
  { slug: "percentage-increase",        name: "Percentage Increase Calculator",category:"algebra", icon: "📈", shortDesc: "Calculate the percentage increase between two values.",       formula: "((New-Old)/Old) × 100", tags: ["percentage increase", "growth"], hasSchema: true },
  { slug: "percentage-decrease",        name: "Percentage Decrease Calculator",category:"algebra", icon: "📉", shortDesc: "Calculate the percentage decrease between two values.",       formula: "((Old-New)/Old) × 100", tags: ["percentage decrease", "reduction"], hasSchema: true },
  { slug: "percentage-difference",      name: "Percentage Difference Calculator",category:"algebra",icon:"↔",  shortDesc: "Find the percentage difference between two values.",          formula: "|a-b|/((a+b)/2) × 100", tags: ["percentage difference"], hasSchema: true },
  { slug: "absolute-difference",        name: "Absolute Difference Calculator",category:"algebra", icon: "||", shortDesc: "Find the absolute difference between two numbers.",           formula: "|a - b|",               tags: ["absolute difference", "math"], hasSchema: true },
  { slug: "simplify-radical-expressions",name:"Simplify Radical Expressions", category:"algebra", icon: "√",  shortDesc: "Simplify radical expressions to their simplest form.",        formula: "√(a×b) = √a × √b",     tags: ["simplify radical", "radical"], hasSchema: true },
  { slug: "solve-for-exponents",        name: "Solve for Exponents",          category: "algebra", icon: "xⁿ", shortDesc: "Solve equations where the variable is in the exponent.",    formula: "aˣ = b → x = log(b)/log(a)", tags: ["exponent equation", "logarithm"], hasSchema: true },

  // ─── FINANCE ─────────────────────────────────────────────────────────────────
  { slug: "compound-interest-calculator",name:"Compound Interest Calculator", category:"finance", icon:"📈",  shortDesc:"Calculate how money grows with compound interest over time.",  formula:"A = P(1 + r/n)^(nt)",   tags:["compound interest","investment","savings"], hasSchema:true },
  { slug: "simple-interest-calculator", name: "Simple Interest Calculator",   category: "finance", icon: "💵", shortDesc: "Calculate simple interest earned on principal over time.",   formula: "I = P × R × T",        tags: ["simple interest", "loan", "savings"], hasSchema: true },
  { slug: "discount-calculator",        name: "Discount Calculator",          category: "finance", icon: "🏷️", shortDesc: "Find the price after discount and amount saved.",             formula: "Sale Price = Original × (1 - Discount%)", tags: ["discount", "sale", "price"], hasSchema: true },
  { slug: "margin-calculator",          name: "Margin Calculator",            category: "finance", icon: "📊", shortDesc: "Calculate gross profit margin and markup percentage.",         formula: "Margin = (Revenue - Cost) / Revenue × 100", tags: ["margin", "profit", "markup"], hasSchema: true },
  { slug: "markup-calculator",          name: "Markup Calculator",            category: "finance", icon: "💲", shortDesc: "Calculate selling price based on cost and markup.",          formula: "Selling Price = Cost × (1 + Markup%)", tags: ["markup", "cost", "price"], hasSchema: true },
  { slug: "vat-calculator",             name: "VAT Calculator",               category: "finance", icon: "🧾", shortDesc: "Add or remove VAT from any price.",                          formula: "Price with VAT = Net × (1 + VAT%)", tags: ["vat", "tax", "price"], hasSchema: true },
  { slug: "energy-consumption-calculator",name:"Energy Consumption Calculator",category:"finance",icon:"⚡",  shortDesc:"Calculate electricity costs from wattage, hours, and rate.",  formula: "Cost = W × H × Rate / 1000", tags: ["energy", "electricity", "cost"], hasSchema: true },
  { slug: "adsense-calculator",         name: "AdSense Calculator",           category: "finance", icon: "💰", shortDesc: "Estimate Google AdSense earnings from page views and CTR.",   formula: "Revenue = Impressions × CTR × CPC / 1000", tags: ["adsense", "earnings", "monetization"], hasSchema: true },
  { slug: "cpv-calculator",             name: "CPV Calculator",               category: "finance", icon: "📺", shortDesc: "Calculate Cost Per View for video ad campaigns.",             formula: "CPV = Total Cost / Views", tags: ["cpv", "advertising", "cost per view"], hasSchema: true },
  { slug: "tithing-calculator",         name: "Tithing Calculator",           category: "finance", icon: "⛪", shortDesc: "Calculate your tithe at 10% of your income.",                formula: "Tithe = Income × 10%",  tags: ["tithe", "donation", "religious", "10%"], hasSchema: true },
  { slug: "poshmark-fee-calculator",    name: "Poshmark Fee Calculator",      category: "finance", icon: "👗", shortDesc: "Calculate Poshmark fees and your net earnings on a sale.",   formula: "Fee: $2.95 under $15, 20% over $15", tags: ["poshmark", "fee", "selling"], hasSchema: true },
  { slug: "youtube-earnings-calculator",name: "YouTube Earnings Calculator",  category: "finance", icon: "▶️", shortDesc: "Estimate YouTube ad revenue from views and RPM.",            formula: "Earnings = Views × RPM / 1000", tags: ["youtube", "earnings", "creator"], hasSchema: true },
  { slug: "commission-calculator",      name: "Commission Calculator",        category: "finance", icon: "💼", shortDesc: "Calculate sales commission from rate and sales amount.",     formula: "Commission = Sales × Rate%", tags: ["commission", "sales", "earnings"], hasSchema: true },
  { slug: "money-calculator",           name: "Money Calculator",             category: "finance", icon: "💵", shortDesc: "Count total value from bills and coins of different denominations.", formula: "Sum of all bill × face values", tags: ["money", "coins", "bills", "counting"], hasSchema: true },

  // ─── LOANS ───────────────────────────────────────────────────────────────────
  { slug: "loan-calculator",            name: "Loan Calculator",              category: "loans",   icon: "🏦", shortDesc: "Calculate monthly loan payments, interest, and total cost.",  formula: "EMI = P × r(1+r)^n / ((1+r)^n-1)", tags: ["loan", "emi", "mortgage"], hasSchema: true },
  { slug: "emi-calculator",             name: "EMI Calculator",               category: "loans",   icon: "📆", shortDesc: "Calculate monthly EMI for home loans and personal loans.",    formula: "EMI = P × r(1+r)^n / ((1+r)^n-1)", tags: ["emi", "loan", "monthly payment"], hasSchema: true },
  { slug: "epf-calculator",             name: "EPF Calculator",               category: "loans",   icon: "🏦", shortDesc: "Calculate Employee Provident Fund balance and maturity.",     formula: "EPF contribution rules",tags: ["epf", "provident fund", "retirement"], hasSchema: true },
  { slug: "fd-calculator",              name: "FD Calculator",                category: "loans",   icon: "📊", shortDesc: "Calculate Fixed Deposit maturity amount and interest.",       formula: "FD = P(1 + r/n)^(nt)", tags: ["fd", "fixed deposit", "bank"], hasSchema: true },
  { slug: "gst-calculator",             name: "GST Calculator",               category: "loans",   icon: "🧾", shortDesc: "Add or remove GST from a price and find tax amount.",          formula: "GST Amount = Original × GST%", tags: ["gst", "tax", "india"], hasSchema: true },
  { slug: "income-tax-calculator",      name: "Income Tax Calculator",        category: "loans",   icon: "📋", shortDesc: "Estimate your income tax liability for the current year.",    formula: "Progressive tax slabs", tags: ["income tax", "tax", "salary"], hasSchema: true },
  { slug: "lumpsum-calculator",         name: "Lumpsum Calculator",           category: "loans",   icon: "💰", shortDesc: "Calculate returns on a one-time lumpsum mutual fund investment.", formula: "Returns = P × (1 + r)^t", tags: ["lumpsum", "investment", "mutual fund"], hasSchema: true },
  { slug: "sip-calculator",             name: "SIP Calculator",               category: "loans",   icon: "📈", shortDesc: "Calculate wealth created by Systematic Investment Plan.",      formula: "SIP = P × ((1+r)^n - 1) / r × (1+r)", tags: ["sip", "mutual fund", "investment"], hasSchema: true },
  { slug: "ppf-calculator",             name: "PPF Calculator",               category: "loans",   icon: "🏦", shortDesc: "Calculate Public Provident Fund maturity and yearly interest.", formula: "15-year lock-in with compounding", tags: ["ppf", "savings", "india"], hasSchema: true },
  { slug: "rd-calculator",              name: "RD Calculator",                category: "loans",   icon: "📆", shortDesc: "Calculate Recurring Deposit maturity amount.",                formula: "RD = P × n + interest", tags: ["rd", "recurring deposit", "savings"], hasSchema: true },
  { slug: "swp-calculator",             name: "SWP Calculator",               category: "loans",   icon: "💸", shortDesc: "Calculate Systematic Withdrawal Plan withdrawals and balance.", formula: "SWP monthly withdrawal", tags: ["swp", "withdrawal", "mutual fund"], hasSchema: true },
  { slug: "xirr-calculator",            name: "XIRR Calculator",              category: "loans",   icon: "📊", shortDesc: "Calculate extended internal rate of return for investments.",  formula: "XIRR = IRR with dates",  tags: ["xirr", "returns", "irr"], hasSchema: true },
  { slug: "mutual-fund-returns",        name: "Mutual Fund Returns Calculator",category:"loans",   icon: "📈", shortDesc: "Estimate mutual fund returns based on NAV and investment.",   formula: "Returns = (Current NAV - Purchase NAV) / Purchase NAV × 100", tags: ["mutual fund", "returns", "nav"], hasSchema: true },

  // ─── STATISTICS ──────────────────────────────────────────────────────────────
  { slug: "average-calculator",         name: "Average Calculator",           category: "statistics", icon: "∑", shortDesc: "Calculate the mean, median, and mode of a dataset.",       formula: "Mean = Σx/n",          tags: ["average", "mean", "statistics"], hasSchema: true },
  { slug: "standard-deviation-calculator",name:"Standard Deviation Calculator",category:"statistics",icon:"σ",  shortDesc:"Calculate the standard deviation of a dataset.",              formula: "σ = √(Σ(x-μ)²/N)",    tags: ["standard deviation", "statistics", "variance"], hasSchema: true },
  { slug: "mean-median-mode-calculator",name: "Mean Median Mode Calculator",  category: "statistics", icon: "📊",shortDesc: "Find the mean, median, and mode of any list of numbers.",  formula: "Mean=Σx/n, Median=middle, Mode=most frequent", tags: ["mean", "median", "mode"], hasSchema: true },
  { slug: "variance-calculator",        name: "Variance Calculator",          category: "statistics", icon: "σ²",shortDesc: "Calculate population and sample variance of a dataset.",    formula: "Var = Σ(x-mean)²/n",   tags: ["variance", "statistics"], hasSchema: true },
  { slug: "median-calculator",          name: "Median Calculator",            category: "statistics", icon: "📏",shortDesc: "Find the median value of a sorted or unsorted dataset.",    formula: "Middle value when sorted",tags: ["median", "statistics", "middle"], hasSchema: true },
  { slug: "z-score-calculator",         name: "Z Score Calculator",           category: "statistics", icon: "z",  shortDesc: "Convert data values to z-scores and find probabilities.",  formula: "z = (x - μ) / σ",      tags: ["z score", "normal distribution", "statistics"], hasSchema: true },
  { slug: "percentile-calculator",      name: "Percentile Calculator",        category: "statistics", icon: "P",  shortDesc: "Find what percentile a value falls in within a dataset.",  formula: "Percentile rank = (L/N) × 100", tags: ["percentile", "statistics", "rank"], hasSchema: true },
  { slug: "quartile-calculator",        name: "Quartile Calculator",          category: "statistics", icon: "Q",  shortDesc: "Find Q1, Q2, Q3 and the interquartile range of data.",     formula: "IQR = Q3 - Q1",         tags: ["quartile", "iqr", "statistics"], hasSchema: true },
  { slug: "interquartile-range",        name: "Interquartile Range Calculator",category:"statistics", icon:"IQR", shortDesc: "Calculate the IQR and identify statistical outliers.",    formula: "IQR = Q3 - Q1",         tags: ["iqr", "quartile", "outlier"], hasSchema: true },
  { slug: "probability-calculator",     name: "Probability Calculator",       category: "statistics", icon: "🎲", shortDesc: "Calculate probability, combinations, and permutations.",   formula: "P(A) = Favorable / Total", tags: ["probability", "statistics", "chance"], hasSchema: true },
  { slug: "normal-distribution",        name: "Normal Distribution Calculator",category:"statistics", icon:"📊",  shortDesc: "Find probabilities and values using the normal distribution.", formula: "z = (x-μ)/σ, look up Φ(z)", tags: ["normal distribution", "bell curve"], hasSchema: true },
  { slug: "percent-error-stat",         name: "Percent Error Calculator",     category: "statistics", icon: "⚠️", shortDesc: "Calculate measurement error as a percentage.",              formula: "|Exp-Theo|/Theo × 100", tags: ["percent error", "accuracy"], hasSchema: true },
  { slug: "confidence-interval",        name: "Confidence Interval Calculator",category:"statistics", icon:"📐",  shortDesc: "Calculate confidence intervals for population means.",     formula: "CI = x̄ ± z*(σ/√n)",   tags: ["confidence interval", "statistics"], hasSchema: true },
  { slug: "p-value-calculator",         name: "P Value Calculator",           category: "statistics", icon: "p",  shortDesc: "Calculate p-value for hypothesis testing.",                formula: "One and two-tailed tests", tags: ["p value", "hypothesis test", "statistics"], hasSchema: true },
  { slug: "sample-size-calculator",     name: "Sample Size Calculator",       category: "statistics", icon: "n",  shortDesc: "Find the sample size needed for statistical significance.", formula: "n = (z×σ/E)²",          tags: ["sample size", "statistics", "survey"], hasSchema: true },
  { slug: "odds-probability",           name: "Odds Probability Calculator",  category: "statistics", icon: "🎲", shortDesc: "Convert odds to probability and vice versa.",               formula: "P = odds / (odds+1)",   tags: ["odds", "probability", "betting"], hasSchema: true },
  { slug: "vote-percentage",            name: "Vote Percentage Calculator",   category: "statistics", icon: "🗳️", shortDesc: "Calculate vote percentages from election results.",          formula: "Vote% = Votes / Total × 100", tags: ["vote", "election", "percentage"], hasSchema: true },
  { slug: "gpa-calculator",             name: "GPA Calculator",               category: "statistics", icon: "🎓", shortDesc: "Calculate cumulative GPA from course grades and credits.",  formula: "GPA = Σ(Grade×Credits) / ΣCredits", tags: ["gpa", "grades", "college"], hasSchema: true },
  { slug: "final-exam-grade",           name: "Final Exam Grade Calculator",  category: "statistics", icon: "📝", shortDesc: "Calculate what you need on your final exam to get your target grade.", formula: "Required = (Target - Current×weight) / FinalWeight", tags: ["final exam", "grade", "calculator"], hasSchema: true },
  { slug: "stem-leaf-plot",             name: "Stem and Leaf Plot Generator", category: "statistics", icon: "📊", shortDesc: "Create stem-and-leaf plots from a dataset.",                formula: "Split digits into stem and leaf", tags: ["stem leaf", "data visualization"], hasSchema: true },
  { slug: "sum-calculator",             name: "Sum Calculator",               category: "statistics", icon: "Σ",  shortDesc: "Add up a list of numbers and find the running total.",       formula: "Σx = x₁+x₂+...+xₙ",  tags: ["sum", "total", "add"], hasSchema: true },
  { slug: "random-name-picker",         name: "Random Name Picker",           category: "statistics", icon: "🎰", shortDesc: "Pick a random name from a list for raffles or selections.", formula: "Random selection",      tags: ["random", "name picker", "raffle"], hasSchema: true },
  { slug: "random-card-generator",      name: "Random Card Generator",        category: "statistics", icon: "🃏", shortDesc: "Generate a random playing card from a 52-card deck.",       formula: "Uniform random selection",tags: ["random card", "playing card"], hasSchema: true },
  { slug: "pin-generator",              name: "PIN Generator Calculator",     category: "statistics", icon: "🔢", shortDesc: "Generate a random PIN of any length.",                      formula: "Random digit generation",tags: ["pin", "random", "security"], hasSchema: true },
  { slug: "statistics-formulas",        name: "Statistics Formulas Sheet",    category: "statistics", icon: "📋", shortDesc: "Quick reference for all key statistics formulas.",          formula: "All stats formulas",    tags: ["statistics", "formulas", "reference"], hasSchema: true },

  // ─── HEALTH ──────────────────────────────────────────────────────────────────
  { slug: "bmi-calculator",             name: "BMI Calculator",               category: "health",  icon: "🏃", shortDesc: "Calculate your Body Mass Index and find your weight category.", formula: "BMI = kg / m²",        tags: ["bmi", "body mass index", "health"], hasSchema: true },
  { slug: "bmr-calculator",             name: "BMR Calculator",               category: "health",  icon: "🔥", shortDesc: "Calculate your Basal Metabolic Rate — calories burned at rest.", formula: "Mifflin-St Jeor equation", tags: ["bmr", "basal metabolic rate", "calories", "health"], hasSchema: true },
  { slug: "calorie-burn-calculator",    name: "Calorie Burn Calculator",      category: "health",  icon: "🏃", shortDesc: "Estimate calories burned during exercise by activity and weight.", formula: "Calories = MET × weight × time", tags: ["calories", "exercise", "burn", "health"], hasSchema: true },
  { slug: "ideal-weight-calculator",    name: "Ideal Weight Calculator",      category: "health",  icon: "⚖️", shortDesc: "Find your ideal body weight based on height and gender.",        formula: "Hamwi / Devine formula", tags: ["ideal weight", "healthy weight", "health"], hasSchema: true },
  { slug: "water-intake-calculator",    name: "Water Intake Calculator",      category: "health",  icon: "💧", shortDesc: "Calculate your daily water intake recommendation by weight.",    formula: "Water = weight × 0.033 L/kg", tags: ["water intake", "hydration", "health"], hasSchema: true },
  { slug: "tdee-calculator",            name: "TDEE Calculator",              category: "health",  icon: "🔥", shortDesc: "Calculate Total Daily Energy Expenditure from BMR and activity level.", formula: "TDEE = BMR × Activity factor", tags: ["tdee", "calories", "maintenance", "health"], hasSchema: true },
  { slug: "body-fat-calculator",        name: "Body Fat Calculator",          category: "health",  icon: "📏", shortDesc: "Estimate body fat percentage using the US Navy circumference method.", formula: "Navy body fat formula",   tags: ["body fat", "body composition", "health"], hasSchema: true },
  { slug: "macro-calculator",           name: "Macro Calculator",             category: "health",  icon: "🥗", shortDesc: "Calculate daily protein, carbohydrate, and fat targets from TDEE.", formula: "Macros from TDEE %",      tags: ["macros", "protein", "carbs", "fat", "nutrition"], hasSchema: true },
  { slug: "heart-rate-calculator",      name: "Heart Rate Calculator",        category: "health",  icon: "❤️", shortDesc: "Find your max heart rate and training zones by age.",              formula: "Max HR = 220 − age",     tags: ["heart rate", "training zones", "cardio", "health"], hasSchema: true },
  { slug: "waist-hip-ratio",            name: "Waist Hip Ratio Calculator",   category: "health",  icon: "📐", shortDesc: "Calculate your waist-to-hip ratio and assess health risk.",        formula: "WHR = waist / hip",      tags: ["waist hip ratio", "whr", "health risk", "health"], hasSchema: true },
  { slug: "lean-body-mass",             name: "Lean Body Mass Calculator",    category: "health",  icon: "💪", shortDesc: "Calculate your lean body mass from weight and body fat percentage.", formula: "LBM = weight × (1 − BF%)", tags: ["lean body mass", "lbm", "body composition", "health"], hasSchema: true },
  { slug: "protein-intake-calculator",  name: "Protein Intake Calculator",    category: "health",  icon: "🥩", shortDesc: "Calculate daily protein requirements based on weight and goals.",   formula: "Protein = 1.6–2.2 g/kg", tags: ["protein", "nutrition", "intake", "health"], hasSchema: true },
  { slug: "calorie-deficit-calculator", name: "Calorie Deficit Calculator",   category: "health",  icon: "⚖️", shortDesc: "Calculate calorie deficit needed to reach your weight loss goal.",  formula: "Deficit = TDEE − target", tags: ["calorie deficit", "weight loss", "health"], hasSchema: true },
  { slug: "pregnancy-due-date",         name: "Pregnancy Due Date Calculator",category: "health",  icon: "🤰", shortDesc: "Estimate your pregnancy due date from the last menstrual period.",  formula: "EDD = LMP + 280 days",   tags: ["pregnancy", "due date", "lmp", "health"], hasSchema: true },
  { slug: "running-pace-calculator",    name: "Running Pace Calculator",      category: "health",  icon: "🏃", shortDesc: "Calculate your running pace, speed, and finish time for any race.", formula: "Pace = time / distance", tags: ["running", "pace", "race", "fitness", "health"], hasSchema: true },
  { slug: "steps-to-calories",          name: "Steps to Calories Calculator", category: "health",  icon: "👟", shortDesc: "Convert daily step count to estimated calories burned.",           formula: "Cal = steps × 0.04",     tags: ["steps", "calories", "pedometer", "health"], hasSchema: true },
  { slug: "bmi-prime",                  name: "BMI Prime Calculator",         category: "health",  icon: "📊", shortDesc: "Calculate BMI Prime — a ratio of BMI to the upper healthy limit.", formula: "BMI Prime = BMI / 25",   tags: ["bmi prime", "bmi", "health"], hasSchema: true },
  { slug: "vo2-max-calculator",         name: "VO2 Max Calculator",           category: "health",  icon: "🫁", shortDesc: "Estimate VO2 max from resting heart rate and max heart rate.",     formula: "VO2max = 15 × HRmax/HRrest", tags: ["vo2 max", "aerobic capacity", "fitness", "health"], hasSchema: true },
  { slug: "blood-pressure-categories",  name: "Blood Pressure Categories",    category: "health",  icon: "🩺", shortDesc: "Classify systolic and diastolic blood pressure by AHA guidelines.", formula: "AHA BP categories",      tags: ["blood pressure", "hypertension", "health"], hasSchema: true },
  { slug: "alcohol-units",              name: "Alcohol Units Calculator",     category: "health",  icon: "🍺", shortDesc: "Calculate alcohol units from drink volume and ABV percentage.",    formula: "Units = ABV% × mL / 1000", tags: ["alcohol", "units", "abv", "health"], hasSchema: true },
  { slug: "body-surface-area",          name: "Body Surface Area Calculator", category: "health",  icon: "📐", shortDesc: "Calculate body surface area using the Mosteller formula.",         formula: "BSA = √(height×weight/3600)", tags: ["body surface area", "bsa", "health", "medical"], hasSchema: true },
  { slug: "smoking-cost-calculator",    name: "Smoking Cost Calculator",      category: "health",  icon: "🚬", shortDesc: "Calculate the yearly financial and health cost of smoking.",       formula: "Cost = packs × price × days", tags: ["smoking", "cost", "health risk", "health"], hasSchema: true },
  { slug: "sleep-calculator",           name: "Sleep Cycle Calculator",       category: "health",  icon: "😴", shortDesc: "Find ideal wake-up times based on 90-minute sleep cycles.",       formula: "Sleep cycles × 90 min",  tags: ["sleep", "sleep cycle", "wake up", "health"], hasSchema: true },
  { slug: "fiber-intake-calculator",    name: "Fiber Intake Calculator",      category: "health",  icon: "🌾", shortDesc: "Calculate daily fiber intake recommendation by age and gender.",   formula: "14g per 1000 kcal",      tags: ["fiber", "dietary fiber", "nutrition", "health"], hasSchema: true },

  // ─── PHYSICS ──────────────────────────────────────────────────────────────────
  { slug: "ohms-law-calculator",        name: "Ohm's Law Calculator",         category: "physics", icon: "⚡", shortDesc: "Calculate voltage, current, or resistance using Ohm's Law.",       formula: "V = I × R",              tags: ["ohms law", "voltage", "current", "resistance", "physics"], hasSchema: true },
  { slug: "kinetic-energy-calculator",  name: "Kinetic Energy Calculator",    category: "physics", icon: "⚡", shortDesc: "Calculate kinetic energy from mass and velocity.",                 formula: "KE = ½mv²",              tags: ["kinetic energy", "physics", "energy"], hasSchema: true },
  { slug: "potential-energy-calculator",name: "Potential Energy Calculator",  category: "physics", icon: "🏔️", shortDesc: "Calculate gravitational potential energy from mass, g, and height.", formula: "PE = mgh",               tags: ["potential energy", "gravity", "physics"], hasSchema: true },
  { slug: "force-calculator",           name: "Force Calculator",             category: "physics", icon: "💥", shortDesc: "Calculate force, mass, or acceleration using Newton's second law.", formula: "F = m × a",              tags: ["force", "newton", "mass", "acceleration", "physics"], hasSchema: true },
  { slug: "velocity-calculator",        name: "Velocity Calculator",          category: "physics", icon: "🚀", shortDesc: "Calculate velocity, distance, or time for uniform motion.",         formula: "v = d / t",              tags: ["velocity", "speed", "distance", "time", "physics"], hasSchema: true },
  { slug: "acceleration-calculator",    name: "Acceleration Calculator",      category: "physics", icon: "📈", shortDesc: "Find acceleration from change in velocity over time.",             formula: "a = Δv / t",             tags: ["acceleration", "velocity", "physics"], hasSchema: true },
  { slug: "work-energy-calculator",     name: "Work & Energy Calculator",     category: "physics", icon: "🔨", shortDesc: "Calculate work done by a force over a distance.",                  formula: "W = F × d × cos(θ)",     tags: ["work", "energy", "force", "physics"], hasSchema: true },
  { slug: "power-physics-calculator",   name: "Power Calculator (Physics)",   category: "physics", icon: "⚡", shortDesc: "Calculate mechanical power from work and time, or force and speed.", formula: "P = W / t",              tags: ["power", "watt", "work", "physics"], hasSchema: true },
  { slug: "pressure-physics-calculator",name: "Pressure Calculator",          category: "physics", icon: "🔧", shortDesc: "Calculate pressure from force and area.",                          formula: "P = F / A",              tags: ["pressure", "force", "area", "physics"], hasSchema: true },
  { slug: "density-calculator",         name: "Density Calculator",           category: "physics", icon: "⚖️", shortDesc: "Calculate density, mass, or volume using ρ = m / V.",              formula: "ρ = m / V",              tags: ["density", "mass", "volume", "physics"], hasSchema: true },
  { slug: "wavelength-calculator",      name: "Wavelength Calculator",        category: "physics", icon: "〰️", shortDesc: "Calculate wavelength, frequency, or wave speed.",                 formula: "λ = v / f",              tags: ["wavelength", "frequency", "wave speed", "physics"], hasSchema: true },
  { slug: "torque-calculator",          name: "Torque Calculator",            category: "physics", icon: "🔩", shortDesc: "Calculate torque from force, radius, and angle.",                  formula: "τ = F × r × sin(θ)",     tags: ["torque", "force", "rotation", "physics"], hasSchema: true },
  { slug: "momentum-calculator",        name: "Momentum Calculator",          category: "physics", icon: "🏈", shortDesc: "Calculate momentum from mass and velocity.",                       formula: "p = m × v",              tags: ["momentum", "mass", "velocity", "physics"], hasSchema: true },
  { slug: "gravitational-force",        name: "Gravitational Force Calculator",category:"physics", icon: "🌍", shortDesc: "Calculate gravitational force between two masses.",                formula: "F = Gm₁m₂/r²",          tags: ["gravity", "gravitational force", "newton", "physics"], hasSchema: true },
  { slug: "electric-power-calculator",  name: "Electric Power Calculator",    category: "physics", icon: "💡", shortDesc: "Calculate electrical power from voltage, current, or resistance.", formula: "P = V × I = I²R = V²/R", tags: ["electric power", "watt", "voltage", "current", "physics"], hasSchema: true },
  { slug: "resistors-series",           name: "Resistors in Series",          category: "physics", icon: "〰️", shortDesc: "Calculate total resistance for resistors connected in series.",    formula: "R = R₁+R₂+R₃",          tags: ["resistors", "series circuit", "resistance", "physics"], hasSchema: true },
  { slug: "resistors-parallel",         name: "Resistors in Parallel",        category: "physics", icon: "⋕",  shortDesc: "Calculate total resistance for resistors connected in parallel.",  formula: "1/R = 1/R₁+1/R₂+1/R₃", tags: ["resistors", "parallel circuit", "resistance", "physics"], hasSchema: true },
  { slug: "free-fall-calculator",       name: "Free Fall Calculator",         category: "physics", icon: "🎯", shortDesc: "Calculate distance, velocity, or time for an object in free fall.", formula: "d = ½gt²",               tags: ["free fall", "gravity", "drop", "physics"], hasSchema: true },
  { slug: "projectile-motion",          name: "Projectile Motion Calculator", category: "physics", icon: "🚀", shortDesc: "Calculate range, height, and time for projectile motion.",         formula: "R = v²sin(2θ)/g",        tags: ["projectile", "range", "trajectory", "physics"], hasSchema: true },
  { slug: "capacitor-charge",           name: "Capacitor Charge Calculator",  category: "physics", icon: "🔋", shortDesc: "Calculate charge, capacitance, or voltage for a capacitor.",       formula: "Q = C × V",              tags: ["capacitor", "charge", "capacitance", "physics"], hasSchema: true },

  // ─── TIME & DATE ─────────────────────────────────────────────────────────────
  { slug: "age-calculator",             name: "Age Calculator",               category: "time",    icon: "🎂", shortDesc: "Calculate your exact age in years, months, and days.",         formula: "Current date - Birth date", tags: ["age", "birthday", "date"], hasSchema: true },
  { slug: "hours-calculator",           name: "Hours Calculator",             category: "time",    icon: "⏱️", shortDesc: "Add and subtract hours and minutes for time tracking.",        formula: "HH:MM arithmetic",     tags: ["hours", "time", "calculator"], hasSchema: true },
  { slug: "countdown-timer",            name: "Countdown Timer",              category: "time",    icon: "⏲️", shortDesc: "Set a countdown to any future date or event.",                formula: "Target - Now = Remaining", tags: ["countdown", "timer", "event"], hasSchema: true },
  { slug: "date-difference",            name: "Date Difference Calculator",   category: "time",    icon: "📅", shortDesc: "Find the number of days between two dates.",                  formula: "Date2 - Date1 = Days",  tags: ["date difference", "days between dates"], hasSchema: true },
  { slug: "business-days",              name: "Business Days Calculator",     category: "time",    icon: "💼", shortDesc: "Count working days between two dates, excluding weekends.",   formula: "Weekdays only",         tags: ["business days", "working days"], hasSchema: true },
  { slug: "time-card-calculator",       name: "Time Card Calculator",         category: "time",    icon: "⏱️", shortDesc: "Calculate total hours worked from time card entries.",         formula: "Sum of daily hours",    tags: ["time card", "payroll", "hours worked"], hasSchema: true },
  { slug: "work-hours-calculator",      name: "Work Hours Calculator",        category: "time",    icon: "⏰", shortDesc: "Calculate weekly work hours and overtime pay.",                formula: "Regular + Overtime hours", tags: ["work hours", "overtime", "payroll"], hasSchema: true },
  { slug: "hours-minutes-calculator",   name: "Hours Minutes Calculator",     category: "time",    icon: "⏱️", shortDesc: "Add, subtract, and convert hours and minutes.",                formula: "HH:MM conversions",    tags: ["hours minutes", "time"], hasSchema: true },
  { slug: "time-to-decimal",            name: "Time to Decimal Calculator",   category: "time",    icon: "→",  shortDesc: "Convert time in HH:MM format to decimal hours.",               formula: "Decimal = H + M/60",   tags: ["time to decimal", "hours"], hasSchema: true },
  { slug: "decimal-to-time",            name: "Decimal to Time Calculator",   category: "time",    icon: "←",  shortDesc: "Convert decimal hours back to hours and minutes.",             formula: "HH:MM from decimal",   tags: ["decimal to time", "hours"], hasSchema: true },
  { slug: "sunrise-sunset",             name: "Sunrise Sunset Calculator",    category: "time",    icon: "🌅", shortDesc: "Find sunrise and sunset times for any location and date.",     formula: "Solar position equations", tags: ["sunrise", "sunset", "solar"], hasSchema: true },
  { slug: "gross-pay-calculator",       name: "Gross Pay Calculator",         category: "time",    icon: "💵", shortDesc: "Calculate gross pay from hourly rate and hours worked.",       formula: "Gross = Hours × Rate",  tags: ["gross pay", "payroll", "salary"], hasSchema: true },
  { slug: "stopwatch-lap-timer",        name: "Stopwatch Lap Timer",          category: "time",    icon: "🏁", shortDesc: "Online stopwatch with lap timing and split recording.",        formula: "Elapsed time tracking", tags: ["stopwatch", "timer", "lap"], hasSchema: true },
  { slug: "age-checker",                name: "Age Checker",                  category: "time",    icon: "✓",  shortDesc: "Check if someone meets a minimum age requirement.",            formula: "Current - DOB ≥ Required age", tags: ["age check", "minimum age"], hasSchema: true },
  { slug: "time-date-difference",       name: "Time Date Difference",         category: "time",    icon: "⏳", shortDesc: "Calculate the exact time difference between two datetime values.", formula: "DateTime2 - DateTime1", tags: ["time difference", "date time"], hasSchema: true },
  { slug: "time-calculator-hms",        name: "Time Calculator H:M:S",        category: "time",    icon: "⏱️", shortDesc: "Add and subtract hours, minutes, and seconds.",                formula: "HH:MM:SS arithmetic",  tags: ["time calculator", "hours minutes seconds"], hasSchema: true },
  { slug: "week-number",                name: "Week Number Calculator",        category: "time",    icon: "📅", shortDesc: "Find the ISO week number of any date.",                        formula: "ISO 8601 week numbering", tags: ["week number", "iso", "date"], hasSchema: true },

  // ─── CONVERTERS: TEMPERATURE ─────────────────────────────────────────────────
  { slug: "celsius-to-fahrenheit",      name: "Celsius to Fahrenheit",        category: "converters", icon: "🌡️", shortDesc: "Convert temperatures from Celsius to Fahrenheit.",          formula: "°F = (°C × 9/5) + 32", tags: ["celsius", "fahrenheit", "temperature"], hasSchema: true },
  { slug: "fahrenheit-to-celsius",      name: "Fahrenheit to Celsius",        category: "converters", icon: "🌡️", shortDesc: "Convert temperatures from Fahrenheit to Celsius.",          formula: "°C = (°F - 32) × 5/9", tags: ["fahrenheit", "celsius", "temperature"], hasSchema: true },
  { slug: "celsius-to-kelvin",          name: "Celsius to Kelvin",            category: "converters", icon: "🌡️", shortDesc: "Convert Celsius temperatures to Kelvin.",                   formula: "K = °C + 273.15",      tags: ["celsius", "kelvin", "temperature"], hasSchema: true },
  { slug: "kelvin-to-celsius",          name: "Kelvin to Celsius",            category: "converters", icon: "🌡️", shortDesc: "Convert Kelvin temperatures to Celsius.",                   formula: "°C = K - 273.15",      tags: ["kelvin", "celsius", "temperature"], hasSchema: true },
  { slug: "fahrenheit-to-kelvin",       name: "Fahrenheit to Kelvin",         category: "converters", icon: "🌡️", shortDesc: "Convert Fahrenheit temperatures to Kelvin.",                formula: "K = (°F - 32) × 5/9 + 273.15", tags: ["fahrenheit", "kelvin"], hasSchema: true },
  { slug: "kelvin-to-fahrenheit",       name: "Kelvin to Fahrenheit",         category: "converters", icon: "🌡️", shortDesc: "Convert Kelvin to Fahrenheit degrees.",                     formula: "°F = (K - 273.15) × 9/5 + 32", tags: ["kelvin", "fahrenheit"], hasSchema: true },
  { slug: "celsius-to-rankine",         name: "Celsius to Rankine",           category: "converters", icon: "🌡️", shortDesc: "Convert Celsius to Rankine temperature scale.",             formula: "R = (°C + 273.15) × 9/5", tags: ["celsius", "rankine", "temperature"], hasSchema: true },
  { slug: "rankine-to-celsius",         name: "Rankine to Celsius",           category: "converters", icon: "🌡️", shortDesc: "Convert Rankine to Celsius temperature.",                   formula: "°C = (R - 491.67) × 5/9", tags: ["rankine", "celsius"], hasSchema: true },
  { slug: "rankine-to-fahrenheit",      name: "Rankine to Fahrenheit",        category: "converters", icon: "🌡️", shortDesc: "Convert Rankine to Fahrenheit temperature.",                formula: "°F = R - 459.67",      tags: ["rankine", "fahrenheit"], hasSchema: true },
  { slug: "rankine-to-kelvin",          name: "Rankine to Kelvin",            category: "converters", icon: "🌡️", shortDesc: "Convert Rankine to Kelvin temperature.",                    formula: "K = R × 5/9",          tags: ["rankine", "kelvin"], hasSchema: true },
  { slug: "celsius-to-delisle",         name: "Celsius to Delisle",           category: "converters", icon: "🌡️", shortDesc: "Convert Celsius to the Delisle temperature scale.",         formula: "De = (100 - °C) × 3/2", tags: ["celsius", "delisle"], hasSchema: true },
  { slug: "celsius-to-newton",          name: "Celsius to Newton",            category: "converters", icon: "🌡️", shortDesc: "Convert Celsius to Newton temperature scale.",              formula: "°N = °C × 33/100",     tags: ["celsius", "newton", "temperature"], hasSchema: true },
  { slug: "celsius-to-reaumur",         name: "Celsius to Réaumur",           category: "converters", icon: "🌡️", shortDesc: "Convert Celsius to Réaumur temperature scale.",             formula: "°Ré = °C × 4/5",       tags: ["celsius", "reaumur", "temperature"], hasSchema: true },
  { slug: "celsius-to-romer",           name: "Celsius to Rømer",             category: "converters", icon: "🌡️", shortDesc: "Convert Celsius to Rømer temperature scale.",               formula: "°Rø = °C × 21/40 + 7.5", tags: ["celsius", "romer", "temperature"], hasSchema: true },

  // ─── CONVERTERS: LENGTH ──────────────────────────────────────────────────────
  { slug: "km-to-miles",               name: "Kilometers to Miles",           category: "converters", icon: "🛣️", shortDesc: "Convert kilometers to miles.",                              formula: "Miles = km × 0.621371", tags: ["km", "miles", "distance"], hasSchema: true },
  { slug: "miles-to-km",               name: "Miles to Kilometers",           category: "converters", icon: "🛣️", shortDesc: "Convert miles to kilometers.",                              formula: "km = Miles × 1.60934", tags: ["miles", "km", "distance"], hasSchema: true },
  { slug: "cm-to-inch",                name: "Centimeter to Inch",            category: "converters", icon: "📏", shortDesc: "Convert centimeters to inches.",                            formula: "in = cm × 0.393701",   tags: ["cm", "inch", "length"], hasSchema: true },
  { slug: "inch-to-cm",                name: "Inch to Centimeter",            category: "converters", icon: "📏", shortDesc: "Convert inches to centimeters.",                            formula: "cm = in × 2.54",       tags: ["inch", "cm", "length"], hasSchema: true },
  { slug: "meter-to-feet",             name: "Meters to Feet",                category: "converters", icon: "📏", shortDesc: "Convert meters to feet.",                                   formula: "ft = m × 3.28084",     tags: ["meters", "feet", "length"], hasSchema: true },
  { slug: "feet-to-meter",             name: "Feet to Meters",                category: "converters", icon: "📏", shortDesc: "Convert feet to meters.",                                   formula: "m = ft × 0.3048",      tags: ["feet", "meters", "length"], hasSchema: true },
  { slug: "meter-to-centimeter",       name: "Meter to Centimeter",           category: "converters", icon: "📏", shortDesc: "Convert meters to centimeters.",                            formula: "cm = m × 100",         tags: ["meter", "centimeter", "length"], hasSchema: true },
  { slug: "meter-to-kilometer",        name: "Meter to Kilometer",            category: "converters", icon: "📏", shortDesc: "Convert meters to kilometers.",                             formula: "km = m / 1000",        tags: ["meter", "kilometer"], hasSchema: true },
  { slug: "meter-to-yard",             name: "Meter to Yard",                 category: "converters", icon: "📏", shortDesc: "Convert meters to yards.",                                  formula: "yd = m × 1.09361",     tags: ["meter", "yard", "length"], hasSchema: true },
  { slug: "yard-to-meter",             name: "Yard to Meter",                 category: "converters", icon: "📏", shortDesc: "Convert yards to meters.",                                  formula: "m = yd × 0.9144",      tags: ["yard", "meter", "length"], hasSchema: true },
  { slug: "kilometer-to-mile",         name: "Kilometer to Mile",             category: "converters", icon: "📏", shortDesc: "Convert kilometers to miles.",                              formula: "mi = km × 0.621371",   tags: ["kilometer", "mile"], hasSchema: true },
  { slug: "mile-to-kilometer",         name: "Mile to Kilometer",             category: "converters", icon: "📏", shortDesc: "Convert miles to kilometers.",                              formula: "km = mi × 1.60934",    tags: ["mile", "kilometer"], hasSchema: true },
  { slug: "millimeter-to-inch",        name: "Millimeter to Inch",            category: "converters", icon: "📏", shortDesc: "Convert millimeters to inches.",                            formula: "in = mm × 0.0393701",  tags: ["millimeter", "inch"], hasSchema: true },
  { slug: "centimeter-to-inch",        name: "Centimeter to Inch",            category: "converters", icon: "📏", shortDesc: "Convert centimeters to inches.",                            formula: "in = cm × 0.393701",   tags: ["centimeter", "inch"], hasSchema: true },

  // ─── CONVERTERS: WEIGHT ──────────────────────────────────────────────────────
  { slug: "kg-to-pounds",              name: "Kilograms to Pounds",           category: "converters", icon: "⚖️", shortDesc: "Convert kilograms to pounds.",                              formula: "lbs = kg × 2.20462",   tags: ["kg", "pounds", "weight"], hasSchema: true },
  { slug: "pounds-to-kg",              name: "Pounds to Kilograms",           category: "converters", icon: "⚖️", shortDesc: "Convert pounds to kilograms.",                              formula: "kg = lbs / 2.20462",   tags: ["pounds", "kg", "weight"], hasSchema: true },
  { slug: "kg-to-stone",               name: "Kilograms to Stone",            category: "converters", icon: "⚖️", shortDesc: "Convert kilograms to stone and pounds.",                    formula: "Stone = kg × 0.157473",tags: ["kg", "stone", "weight"], hasSchema: true },
  { slug: "stone-to-kg",               name: "Stone to Kilograms",            category: "converters", icon: "⚖️", shortDesc: "Convert stone to kilograms.",                               formula: "kg = stone × 6.35029", tags: ["stone", "kg", "weight"], hasSchema: true },
  { slug: "kg-to-ton",                 name: "Kilograms to Ton",              category: "converters", icon: "⚖️", shortDesc: "Convert kilograms to metric tons.",                         formula: "ton = kg / 1000",      tags: ["kg", "ton", "weight"], hasSchema: true },
  { slug: "ton-to-kg",                 name: "Ton to Kilograms",              category: "converters", icon: "⚖️", shortDesc: "Convert metric tons to kilograms.",                         formula: "kg = ton × 1000",      tags: ["ton", "kg", "weight"], hasSchema: true },
  { slug: "gram-to-ounce",             name: "Gram to Ounce",                 category: "converters", icon: "⚖️", shortDesc: "Convert grams to ounces.",                                  formula: "oz = g × 0.035274",    tags: ["gram", "ounce", "weight"], hasSchema: true },
  { slug: "ounce-to-gram",             name: "Ounce to Gram",                 category: "converters", icon: "⚖️", shortDesc: "Convert ounces to grams.",                                  formula: "g = oz × 28.3495",     tags: ["ounce", "gram", "weight"], hasSchema: true },
  { slug: "kilogram-to-gram",          name: "Kilogram to Gram",              category: "converters", icon: "⚖️", shortDesc: "Convert kilograms to grams.",                               formula: "g = kg × 1000",        tags: ["kilogram", "gram", "weight"], hasSchema: true },
  { slug: "kilogram-to-pound",         name: "Kilogram to Pound",             category: "converters", icon: "⚖️", shortDesc: "Convert kilograms to pounds.",                              formula: "lb = kg × 2.20462",    tags: ["kilogram", "pound", "weight"], hasSchema: true },
  { slug: "carat-to-gram",             name: "Carat to Gram",                 category: "converters", icon: "💎", shortDesc: "Convert carats to grams for gem and metal weight.",         formula: "g = ct × 0.2",         tags: ["carat", "gram", "jewelry"], hasSchema: true },
  { slug: "ton-metric-to-pound",       name: "Metric Ton to Pound",           category: "converters", icon: "⚖️", shortDesc: "Convert metric tons to pounds.",                            formula: "lb = t × 2204.62",     tags: ["metric ton", "pound", "weight"], hasSchema: true },

  // ─── CONVERTERS: VOLUME ──────────────────────────────────────────────────────
  { slug: "liter-to-gallon",           name: "Liter to Gallon",               category: "converters", icon: "🥛", shortDesc: "Convert liters to US gallons.",                             formula: "gal = L × 0.264172",   tags: ["liter", "gallon", "volume"], hasSchema: true },
  { slug: "gallon-to-liter",           name: "Gallon to Liter",               category: "converters", icon: "🥛", shortDesc: "Convert US gallons to liters.",                             formula: "L = gal × 3.78541",    tags: ["gallon", "liter", "volume"], hasSchema: true },
  { slug: "cup-to-ml",                 name: "Cup to Milliliter",             category: "converters", icon: "☕", shortDesc: "Convert cups to milliliters.",                              formula: "mL = cups × 236.588",  tags: ["cup", "ml", "volume"], hasSchema: true },
  { slug: "ml-to-cup",                 name: "Milliliter to Cup",             category: "converters", icon: "☕", shortDesc: "Convert milliliters to cups.",                              formula: "cups = mL / 236.588",  tags: ["ml", "cup", "volume"], hasSchema: true },
  { slug: "pint-to-liter",             name: "Pint to Liter",                 category: "converters", icon: "🍺", shortDesc: "Convert pints to liters.",                                  formula: "L = pt × 0.473176",    tags: ["pint", "liter", "volume"], hasSchema: true },
  { slug: "liter-to-pint",             name: "Liter to Pint",                 category: "converters", icon: "🍺", shortDesc: "Convert liters to pints.",                                  formula: "pt = L × 2.11338",     tags: ["liter", "pint", "volume"], hasSchema: true },
  { slug: "ml-to-oz",                  name: "Milliliter to Fluid Ounce",     category: "converters", icon: "💧", shortDesc: "Convert milliliters to fluid ounces.",                      formula: "fl oz = mL × 0.033814",tags: ["ml", "oz", "fluid ounce"], hasSchema: true },
  { slug: "oz-to-ml",                  name: "Fluid Ounce to Milliliter",     category: "converters", icon: "💧", shortDesc: "Convert fluid ounces to milliliters.",                      formula: "mL = fl oz × 29.5735", tags: ["oz", "ml", "volume"], hasSchema: true },
  { slug: "cubic-meter-to-cubic-foot", name: "Cubic Meter to Cubic Foot",     category: "converters", icon: "📦", shortDesc: "Convert cubic meters to cubic feet.",                       formula: "ft³ = m³ × 35.3147",   tags: ["cubic meter", "cubic foot", "volume"], hasSchema: true },

  // ─── CONVERTERS: SPEED ───────────────────────────────────────────────────────
  { slug: "kmh-to-mph",                name: "km/h to mph",                   category: "converters", icon: "🚗", shortDesc: "Convert kilometers per hour to miles per hour.",             formula: "mph = km/h × 0.621371",tags: ["kmh", "mph", "speed"], hasSchema: true },
  { slug: "mph-to-kmh",                name: "mph to km/h",                   category: "converters", icon: "🚗", shortDesc: "Convert miles per hour to kilometers per hour.",             formula: "km/h = mph × 1.60934", tags: ["mph", "kmh", "speed"], hasSchema: true },
  { slug: "kmh-to-ms",                 name: "km/h to m/s",                   category: "converters", icon: "⚡", shortDesc: "Convert kilometers per hour to meters per second.",          formula: "m/s = km/h / 3.6",     tags: ["kmh", "ms", "speed"], hasSchema: true },
  { slug: "ms-to-kmh",                 name: "m/s to km/h",                   category: "converters", icon: "⚡", shortDesc: "Convert meters per second to kilometers per hour.",          formula: "km/h = m/s × 3.6",     tags: ["ms", "kmh", "speed"], hasSchema: true },
  { slug: "kmh-to-knot",               name: "km/h to Knot",                  category: "converters", icon: "⛵", shortDesc: "Convert kilometers per hour to nautical knots.",             formula: "kt = km/h × 0.539957", tags: ["kmh", "knot", "speed"], hasSchema: true },
  { slug: "knot-to-kmh",               name: "Knot to km/h",                  category: "converters", icon: "⛵", shortDesc: "Convert nautical knots to kilometers per hour.",             formula: "km/h = kt × 1.852",    tags: ["knot", "kmh", "speed"], hasSchema: true },
  { slug: "knot-to-mph",               name: "Knot to mph",                   category: "converters", icon: "⛵", shortDesc: "Convert nautical knots to miles per hour.",                 formula: "mph = kt × 1.15078",   tags: ["knot", "mph", "speed"], hasSchema: true },
  { slug: "meter-per-second-to-mph",   name: "m/s to mph",                    category: "converters", icon: "🏃", shortDesc: "Convert meters per second to miles per hour.",              formula: "mph = m/s × 2.23694",  tags: ["ms", "mph", "speed"], hasSchema: true },
  { slug: "mph-to-ms",                 name: "mph to m/s",                    category: "converters", icon: "🏃", shortDesc: "Convert miles per hour to meters per second.",              formula: "m/s = mph × 0.44704",  tags: ["mph", "ms", "speed"], hasSchema: true },

  // ─── CONVERTERS: PRESSURE ────────────────────────────────────────────────────
  { slug: "psi-to-bar",                name: "PSI to Bar",                    category: "converters", icon: "🔧", shortDesc: "Convert PSI to Bar pressure.",                              formula: "bar = psi × 0.0689476",tags: ["psi", "bar", "pressure"], hasSchema: true },
  { slug: "bar-to-psi",                name: "Bar to PSI",                    category: "converters", icon: "🔧", shortDesc: "Convert Bar to PSI pressure.",                              formula: "psi = bar × 14.5038",  tags: ["bar", "psi", "pressure"], hasSchema: true },
  { slug: "pascal-to-psi",             name: "Pascal to PSI",                 category: "converters", icon: "🔧", shortDesc: "Convert Pascal to PSI pressure.",                           formula: "psi = Pa × 0.000145038",tags:["pascal", "psi", "pressure"], hasSchema: true },
  { slug: "psi-to-pascal",             name: "PSI to Pascal",                 category: "converters", icon: "🔧", shortDesc: "Convert PSI to Pascal pressure.",                           formula: "Pa = psi × 6894.76",   tags: ["psi", "pascal", "pressure"], hasSchema: true },
  { slug: "atm-to-pascal",             name: "ATM to Pascal",                 category: "converters", icon: "🔧", shortDesc: "Convert atmospheres to Pascals.",                           formula: "Pa = atm × 101325",    tags: ["atm", "pascal", "pressure"], hasSchema: true },
  { slug: "pascal-to-atm",             name: "Pascal to ATM",                 category: "converters", icon: "🔧", shortDesc: "Convert Pascals to atmospheres.",                           formula: "atm = Pa / 101325",    tags: ["pascal", "atm", "pressure"], hasSchema: true },
  { slug: "atmosphere-to-pascal",      name: "Atmosphere to Pascal",          category: "converters", icon: "🔧", shortDesc: "Convert atmospheric pressure to Pascals.",                  formula: "Pa = atm × 101325",    tags: ["atmosphere", "pascal"], hasSchema: true },

  // ─── CONVERTERS: ENERGY ──────────────────────────────────────────────────────
  { slug: "joule-to-calorie",          name: "Joule to Calorie",              category: "converters", icon: "⚡", shortDesc: "Convert joules to calories.",                               formula: "cal = J × 0.239006",   tags: ["joule", "calorie", "energy"], hasSchema: true },
  { slug: "calorie-to-joule",          name: "Calorie to Joule",              category: "converters", icon: "⚡", shortDesc: "Convert calories to joules.",                               formula: "J = cal × 4.184",      tags: ["calorie", "joule", "energy"], hasSchema: true },
  { slug: "btu-to-joule",              name: "BTU to Joule",                  category: "converters", icon: "🔥", shortDesc: "Convert British Thermal Units to Joules.",                  formula: "J = BTU × 1055.06",    tags: ["btu", "joule", "energy"], hasSchema: true },
  { slug: "joule-to-btu",              name: "Joule to BTU",                  category: "converters", icon: "🔥", shortDesc: "Convert Joules to British Thermal Units.",                  formula: "BTU = J × 0.000947817",tags: ["joule", "btu", "energy"], hasSchema: true },
  { slug: "kwh-to-joule",              name: "kWh to Joule",                  category: "converters", icon: "⚡", shortDesc: "Convert kilowatt-hours to joules.",                         formula: "J = kWh × 3,600,000",  tags: ["kwh", "joule", "energy"], hasSchema: true },
  { slug: "joule-to-kwh",              name: "Joule to kWh",                  category: "converters", icon: "⚡", shortDesc: "Convert joules to kilowatt-hours.",                         formula: "kWh = J / 3,600,000",  tags: ["joule", "kwh", "energy"], hasSchema: true },
  { slug: "btu-per-hour-to-watt",      name: "BTU/hr to Watt",                category: "converters", icon: "💡", shortDesc: "Convert BTU per hour to Watts.",                            formula: "W = BTU/hr × 0.29307", tags: ["btu", "watt", "power"], hasSchema: true },
  { slug: "watt-to-horsepower",        name: "Watt to Horsepower",            category: "converters", icon: "🐎", shortDesc: "Convert Watts to mechanical horsepower.",                   formula: "hp = W / 745.7",       tags: ["watt", "horsepower", "power"], hasSchema: true },
  { slug: "horsepower-to-watt",        name: "Horsepower to Watt",            category: "converters", icon: "🐎", shortDesc: "Convert horsepower to Watts.",                              formula: "W = hp × 745.7",       tags: ["horsepower", "watt", "power"], hasSchema: true },
  { slug: "kilowatt-to-horsepower",    name: "Kilowatt to Horsepower",        category: "converters", icon: "🐎", shortDesc: "Convert kilowatts to horsepower.",                          formula: "hp = kW × 1.34102",    tags: ["kilowatt", "horsepower", "power"], hasSchema: true },

  // ─── CONVERTERS: DATA STORAGE ────────────────────────────────────────────────
  { slug: "binary-to-decimal",         name: "Binary to Decimal",             category: "converters", icon: "💻", shortDesc: "Convert binary numbers to decimal.",                        formula: "Σ(bᵢ × 2ⁱ)",          tags: ["binary", "decimal", "number system"], hasSchema: true },
  { slug: "decimal-to-binary",         name: "Decimal to Binary",             category: "converters", icon: "💻", shortDesc: "Convert decimal numbers to binary.",                        formula: "Divide by 2, track remainders", tags: ["decimal", "binary", "number system"], hasSchema: true },
  { slug: "binary-to-hex",             name: "Binary to Hexadecimal",         category: "converters", icon: "💻", shortDesc: "Convert binary numbers to hexadecimal.",                    formula: "Group binary into 4-bit nibbles", tags: ["binary", "hex", "number system"], hasSchema: true },
  { slug: "hex-to-binary",             name: "Hexadecimal to Binary",         category: "converters", icon: "💻", shortDesc: "Convert hexadecimal numbers to binary.",                    formula: "Each hex digit = 4 bits", tags: ["hex", "binary", "number system"], hasSchema: true },
  { slug: "hex-to-decimal",            name: "Hexadecimal to Decimal",        category: "converters", icon: "💻", shortDesc: "Convert hexadecimal to decimal numbers.",                   formula: "Σ(hᵢ × 16ⁱ)",         tags: ["hex", "decimal", "number system"], hasSchema: true },
  { slug: "decimal-to-hex",            name: "Decimal to Hexadecimal",        category: "converters", icon: "💻", shortDesc: "Convert decimal to hexadecimal numbers.",                   formula: "Divide by 16, track remainders", tags: ["decimal", "hex", "number system"], hasSchema: true },
  { slug: "decimal-to-octal",          name: "Decimal to Octal",              category: "converters", icon: "💻", shortDesc: "Convert decimal numbers to octal.",                         formula: "Divide by 8, track remainders", tags: ["decimal", "octal", "number system"], hasSchema: true },
  { slug: "octal-to-decimal",          name: "Octal to Decimal",              category: "converters", icon: "💻", shortDesc: "Convert octal numbers to decimal.",                         formula: "Σ(oᵢ × 8ⁱ)",          tags: ["octal", "decimal", "number system"], hasSchema: true },

  // ─── CONVERTERS: AREA ────────────────────────────────────────────────────────
  { slug: "acre-to-hectare",           name: "Acre to Hectare",               category: "converters", icon: "🌾", shortDesc: "Convert acres to hectares.",                                formula: "ha = ac × 0.404686",   tags: ["acre", "hectare", "area"], hasSchema: true },
  { slug: "hectare-to-acre",           name: "Hectare to Acre",               category: "converters", icon: "🌾", shortDesc: "Convert hectares to acres.",                                formula: "ac = ha × 2.47105",    tags: ["hectare", "acre", "area"], hasSchema: true },
  { slug: "acre-to-square-meter",      name: "Acre to Square Meter",          category: "converters", icon: "🌾", shortDesc: "Convert acres to square meters.",                           formula: "m² = ac × 4046.86",    tags: ["acre", "square meter", "area"], hasSchema: true },
  { slug: "sqft-to-sqm",               name: "Square Feet to Square Meters",  category: "converters", icon: "📐", shortDesc: "Convert square feet to square meters.",                     formula: "m² = ft² × 0.092903",  tags: ["sqft", "sqm", "area"], hasSchema: true },
  { slug: "sqm-to-sqft",               name: "Square Meters to Square Feet",  category: "converters", icon: "📐", shortDesc: "Convert square meters to square feet.",                     formula: "ft² = m² × 10.7639",   tags: ["sqm", "sqft", "area"], hasSchema: true },
  { slug: "sqm-to-acre",               name: "Square Meters to Acres",        category: "converters", icon: "🌾", shortDesc: "Convert square meters to acres.",                           formula: "ac = m² / 4046.86",    tags: ["sqm", "acre", "area"], hasSchema: true },
  { slug: "square-foot-to-sqm",        name: "Square Foot to Square Meter",   category: "converters", icon: "📐", shortDesc: "Convert square feet to square meters.",                     formula: "m² = ft² × 0.092903",  tags: ["square foot", "square meter"], hasSchema: true },
  { slug: "square-kilometer-to-sqm",   name: "Square Kilometer to Square Meter",category:"converters",icon:"📐", shortDesc: "Convert square kilometers to square meters.",               formula: "m² = km² × 1,000,000", tags: ["square km", "square meter"], hasSchema: true },
  { slug: "square-meter-to-sqkm",      name: "Square Meter to Square Kilometer",category:"converters",icon:"📐", shortDesc: "Convert square meters to square kilometers.",               formula: "km² = m² / 1,000,000", tags: ["square meter", "square km"], hasSchema: true },

  // ─── CONVERTERS: TIME ────────────────────────────────────────────────────────
  { slug: "minute-to-hour",            name: "Minute to Hour",                category: "converters", icon: "⏱️", shortDesc: "Convert minutes to hours and minutes.",                     formula: "H = min / 60",         tags: ["minute", "hour", "time"], hasSchema: true },
  { slug: "hour-to-day",               name: "Hour to Day",                   category: "converters", icon: "📅", shortDesc: "Convert hours to days.",                                    formula: "Days = h / 24",        tags: ["hour", "day", "time"], hasSchema: true },
  { slug: "second-to-minute",          name: "Second to Minute",              category: "converters", icon: "⏱️", shortDesc: "Convert seconds to minutes.",                               formula: "min = s / 60",         tags: ["second", "minute", "time"], hasSchema: true },
  { slug: "day-to-week",               name: "Day to Week",                   category: "converters", icon: "📅", shortDesc: "Convert days to weeks.",                                    formula: "Weeks = days / 7",     tags: ["day", "week", "time"], hasSchema: true },
  { slug: "percent-to-ppm",            name: "Percent to PPM",                category: "converters", icon: "🔬", shortDesc: "Convert percent concentration to parts per million.",       formula: "PPM = % × 10,000",     tags: ["percent", "ppm", "concentration"], hasSchema: true },
  { slug: "ppm-to-percent",            name: "PPM to Percent",                category: "converters", icon: "🔬", shortDesc: "Convert parts per million to percentage.",                  formula: "% = PPM / 10,000",     tags: ["ppm", "percent", "concentration"], hasSchema: true },
  { slug: "ppm-to-ppb",                name: "PPM to PPB",                    category: "converters", icon: "🔬", shortDesc: "Convert parts per million to parts per billion.",           formula: "PPB = PPM × 1000",     tags: ["ppm", "ppb", "concentration"], hasSchema: true },
  { slug: "ppb-to-ppm",                name: "PPB to PPM",                    category: "converters", icon: "🔬", shortDesc: "Convert parts per billion to parts per million.",           formula: "PPM = PPB / 1000",     tags: ["ppb", "ppm"], hasSchema: true },
  { slug: "ppm-to-ppt",                name: "PPM to PPT",                    category: "converters", icon: "🔬", shortDesc: "Convert parts per million to parts per trillion.",          formula: "PPT = PPM × 1,000,000",tags: ["ppm", "ppt"], hasSchema: true },
  { slug: "ppt-to-ppm",                name: "PPT to PPM",                    category: "converters", icon: "🔬", shortDesc: "Convert parts per trillion to parts per million.",          formula: "PPM = PPT / 1,000,000",tags: ["ppt", "ppm"], hasSchema: true },
];

// Build slug → entry map
export const REGISTRY_MAP: Record<string, RegistryEntry> = Object.fromEntries(
  ALL_CALCULATORS.map((c) => [c.slug, c])
);

// Build category → entries map
export const BY_CATEGORY: Record<string, RegistryEntry[]> = {};
for (const entry of ALL_CALCULATORS) {
  if (!BY_CATEGORY[entry.category]) BY_CATEGORY[entry.category] = [];
  BY_CATEGORY[entry.category].push(entry);
}

export function getEntry(slug: string): RegistryEntry | undefined {
  return REGISTRY_MAP[slug];
}

export function getRelated(entry: RegistryEntry, limit = 5): RegistryEntry[] {
  return ALL_CALCULATORS
    .filter(
      (e) =>
        e.slug !== entry.slug &&
        (e.category === entry.category ||
          e.tags.some((t) => entry.tags.includes(t)))
    )
    .slice(0, limit);
}
