import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { AppShell } from "@/components/layout/AppShell";
import { EmbedDetector } from "@/components/layout/EmbedDetector";
import { ThemeProvider } from "@/components/ui/ThemeProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  metadataBase: new URL("https://calcunit.net"),
  title: {
    default: "CalcUnit.net — Free Online Calculators",
    template: "%s",
  },
  description:
    "1,000+ free online calculators for math, finance, health, physics, and unit conversion. Instant results as you type. No sign-up. Works offline.",
  manifest: "/manifest.json",
  icons: {
    icon: [
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/icon-192.png",      sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png",      sizes: "512x512", type: "image/png" },
    ],
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
    shortcut: "/favicon-32x32.png",
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "CalcUnit",
  },
  openGraph: {
    type: "website",
    siteName: "CalcUnit",
    title: "CalcUnit — Dynamic Calculator Platform",
    description: "Schema-driven calculators for Finance, Health, Math & Physics",
    // og:image is auto-generated by src/app/opengraph-image.tsx
  },
};

export const viewport: Viewport = {
  themeColor: "#6366f1",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable}`} suppressHydrationWarning>
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="preconnect" href="https://www.googletagmanager.com" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="theme-color" content="#6366f1" />
        <meta name="msvalidate.01" content="XXXXXXXXXXXXXXXXXXX" />



        {/* Site-wide JSON-LD: Organization + WebSite (enables sitelinks searchbox) */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@graph": [
                {
                  "@type": "Organization",
                  "@id": "https://calcunit.net/#organization",
                  name: "CalcUnit",
                  url: "https://calcunit.net",
                  logo: { "@type": "ImageObject", url: "https://calcunit.net/icon-512.png", width: 512, height: 512 },
                  sameAs: ["https://x.com", "https://facebook.com"],
                },
                {
                  "@type": "WebSite",
                  "@id": "https://calcunit.net/#website",
                  name: "CalcUnit",
                  url: "https://calcunit.net",
                  publisher: { "@id": "https://calcunit.net/#organization" },
                  potentialAction: {
                    "@type": "SearchAction",
                    target: { "@type": "EntryPoint", urlTemplate: "https://calcunit.net/?q={search_term_string}" },
                    "query-input": "required name=search_term_string",
                  },
                },
              ],
            }),
          }}
        />

        {/* Google Analytics — deferred to browser idle time so it never slows page load */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-2EHPV7HS8K"
          strategy="lazyOnload"
        />
        <Script id="ga-init" strategy="lazyOnload">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-2EHPV7HS8K');
          `}
        </Script>
      </head>
      <body className={`${inter.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <EmbedDetector />
          <AppShell>{children}</AppShell>
        </ThemeProvider>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              if ('serviceWorker' in navigator && window.location.hostname !== 'localhost' && window.location.hostname !== '127.0.0.1') {
                window.addEventListener('load', () => {
                  navigator.serviceWorker.register('/sw.js');
                });
              }
            `,
          }}
        />
      </body>
    </html>
  );
}
